# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='color',
            field=models.CharField(default='GREEN', max_length=50),
        ),
    ]
