# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='color',
        ),
    ]
